// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "recette/v1alpha/recette.proto" (package "recette.v1alpha", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RecetteCRUDService } from "./recette";
import type { DeleteResponse } from "./recette";
import type { DeleteRequest } from "./recette";
import type { UpdateResponse } from "./recette";
import type { UpdateRequest } from "./recette";
import type { AddResponse } from "./recette";
import type { AddRequest } from "./recette";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetResponse } from "./recette";
import type { GetRequest } from "./recette";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service recette.v1alpha.RecetteCRUDService
 */
export interface IRecetteCRUDServiceClient {
    /**
     * @generated from protobuf rpc: Get(recette.v1alpha.GetRequest) returns (recette.v1alpha.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse>;
    /**
     * @generated from protobuf rpc: Add(recette.v1alpha.AddRequest) returns (recette.v1alpha.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse>;
    /**
     * @generated from protobuf rpc: Update(recette.v1alpha.UpdateRequest) returns (recette.v1alpha.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse>;
    /**
     * @generated from protobuf rpc: Delete(recette.v1alpha.DeleteRequest) returns (recette.v1alpha.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse>;
}
/**
 * @generated from protobuf service recette.v1alpha.RecetteCRUDService
 */
export class RecetteCRUDServiceClient implements IRecetteCRUDServiceClient, ServiceInfo {
    typeName = RecetteCRUDService.typeName;
    methods = RecetteCRUDService.methods;
    options = RecetteCRUDService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Get(recette.v1alpha.GetRequest) returns (recette.v1alpha.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRequest, GetResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Add(recette.v1alpha.AddRequest) returns (recette.v1alpha.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddRequest, AddResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Update(recette.v1alpha.UpdateRequest) returns (recette.v1alpha.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRequest, UpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Delete(recette.v1alpha.DeleteRequest) returns (recette.v1alpha.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRequest, DeleteResponse>("unary", this._transport, method, opt, input);
    }
}
