// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "nutrition/v1alpha/nutrition.proto" (package "nutrition.v1alpha", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { NutritionCRUDService } from "./nutrition";
import type { DeleteResponse } from "./nutrition";
import type { DeleteRequest } from "./nutrition";
import type { UpdateResponse } from "./nutrition";
import type { UpdateRequest } from "./nutrition";
import type { AddResponse } from "./nutrition";
import type { AddRequest } from "./nutrition";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetResponse } from "./nutrition";
import type { GetRequest } from "./nutrition";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service nutrition.v1alpha.NutritionCRUDService
 */
export interface INutritionCRUDServiceClient {
    /**
     * @generated from protobuf rpc: Get(nutrition.v1alpha.GetRequest) returns (nutrition.v1alpha.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse>;
    /**
     * @generated from protobuf rpc: Add(nutrition.v1alpha.AddRequest) returns (nutrition.v1alpha.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse>;
    /**
     * @generated from protobuf rpc: Update(nutrition.v1alpha.UpdateRequest) returns (nutrition.v1alpha.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse>;
    /**
     * @generated from protobuf rpc: Delete(nutrition.v1alpha.DeleteRequest) returns (nutrition.v1alpha.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse>;
}
/**
 * @generated from protobuf service nutrition.v1alpha.NutritionCRUDService
 */
export class NutritionCRUDServiceClient implements INutritionCRUDServiceClient, ServiceInfo {
    typeName = NutritionCRUDService.typeName;
    methods = NutritionCRUDService.methods;
    options = NutritionCRUDService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Get(nutrition.v1alpha.GetRequest) returns (nutrition.v1alpha.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRequest, GetResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Add(nutrition.v1alpha.AddRequest) returns (nutrition.v1alpha.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddRequest, AddResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Update(nutrition.v1alpha.UpdateRequest) returns (nutrition.v1alpha.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRequest, UpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Delete(nutrition.v1alpha.DeleteRequest) returns (nutrition.v1alpha.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRequest, DeleteResponse>("unary", this._transport, method, opt, input);
    }
}
